stages:
  - mavenbuild
  - maventest
  - mavendeploy
  - androidbuild
  - androidtest

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

maven-build:
  stage: mavenbuild
  tags:
    - springboot_tag
  script:
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
    - export PATH=$JAVA_HOME/bin:$PATH
    - cd Backend
    - mvn package
  artifacts:
    paths:
      - Backend/target/*.jar
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      changes:
        - Backend/**/*
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - Backend/**/*

maven-test:
  stage: maventest
  tags:
    - springboot_tag
  script:
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
    - export PATH=$JAVA_HOME/bin:$PATH
    - cd Backend
    - mvn test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      changes:
        - Backend/**/*
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - Backend/**/*

auto-deploy:
  stage: mavendeploy
  tags:
    - springboot_tag
  script:
    - cd Backend
    - sudo mv target/*.jar /target/web-demo.jar
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
  rules:
    - if: $CI_COMMIT_BRANCH == "main"  # Only deploy on main branch
      changes:
        - Backend/**/*

android-build:
  image: afirefly/android-ci:java17
  stage: androidbuild
  tags:
    - android_tag
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  script:
    - cd Frontend
    - ./gradlew build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      changes:
        - Frontend/**/*
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - Frontend/**/*

android-test:
  image: afirefly/android-ci:java17
  stage: androidtest
  tags:
    - android_tag
  variables:
    ANDROID_HOME: "/usr/lib/android-sdk"
    ANDROID_SDK_ROOT: "/usr/lib/android-sdk"
    ANDROID_COMPILE_SDK: "34"
    ANDROID_BUILD_TOOLS: "34.0.0"
    ANDROID_SDK_TOOLS: "9477386"
    AVD_NAME: "test_device"
    EMULATOR_API_LEVEL: "29"
    EMULATOR_ABI: "x86_64"
    EMULATOR_TAG: "google_apis"
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
    - export PATH=${ANDROID_HOME}/cmdline-tools/tools/bin:${ANDROID_HOME}/platform-tools:${PATH}
    - yes | sdkmanager --licenses || true
    - sdkmanager --install "emulator" "platform-tools" "platforms;android-${ANDROID_COMPILE_SDK}" "build-tools;${ANDROID_BUILD_TOOLS}" "system-images;android-${EMULATOR_API_LEVEL};${EMULATOR_TAG};${EMULATOR_ABI}"
    - echo "no" | avdmanager create avd -n ${AVD_NAME} -k "system-images;android-${EMULATOR_API_LEVEL};${EMULATOR_TAG};${EMULATOR_ABI}"
  script:
    - cd Frontend
    - ${ANDROID_HOME}/emulator/emulator -avd ${AVD_NAME} -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect -no-snapshot &
    - timeout 300 adb wait-for-device shell 'while [[ $(getprop sys.boot_completed) != "1" ]]; do sleep 5; done' || exit 1
    - ./gradlew connectedAndroidTest
  artifacts:
    paths:
      - Frontend/app/build/reports/androidTests/
    when: always
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      changes:
        - Frontend/**/*
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - Frontend/**/*